services:
  german-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile

    container_name: german-learning-api
    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "3001"

    networks:
      - shared-network

  german-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://german-api.jose-manuel-rodriguez-varona-005.com/api

    container_name: german-learning-web
    restart: unless-stopped

    expose:
      - "3000"

    depends_on:
      - german-api

    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: growth-path_growth-path-network